### ISSUE TITLE
No .crx file

### ISSUE THREAD

**Issue by Mks4747** [NorbertCode/CDA-Downloader-Extension#1] opened 2024-09-29 11:05 UTC
When I download .zip file and try to upload it, there's no .crx file, so Chrome shows an error message "Manifesto has been not found"

**Comment by NorbertCode** [comment] 2024-09-29 12:33
Unfortunately I wasn't able to reproduce your issue. Once you have downloaded the .zip and extracted it, you should be able to load it unpacked. Would greatly appreciate some more info on that.

Regarding the .crx file, it was available on the [releases page](https://github.com/NorbertCode/CDA-Downloader-Extension/releases), though you couldn't download it due to Chrome trying to auto-install it. I just now put it in a .zip file, so it should download normally. I suggest you try using that. Just extract it and drag and drop the .crx file onto your browser's extension management page.

Please get back to me if any other issues arise or if this fixes your problem. Thanks for your feedback.

**Comment by Mks4747** [comment] 2024-09-29 17:35
Hi,

I’ve followed your instructions and downloaded .crx file via releases page, then unpacked it to already existing folder.

Now the browser has installed the extension without any problems.

Thank you for your help!

 

Best regards

Maksymilian

 

PS. You can upload .crx file into code page (https://github.com/NorbertCode/CDA-Downloader-Extension/tree/dev), so the browser would automaticlly download all the content.

Thank you for help again! The extension is working without any problems whatsoever!

**Comment by NorbertCode** [comment] 2024-09-29 18:04
Glad I could help and, again, thanks for the feedback. I hope you get some use out of this extension. I'm closing the issue now.

**Closed as completed by NorbertCode** 2024-09-29 18:04 UTC
